Zephir / Basel hinzugefügt
FriendsOfREDAXO/community pull request #315
Opened 2021-03-27 20:25 UTC by dtpop

2021-03-27 20:55 UTC, schuer commented
Hey @dtpop, die Community-Map ist für Personen gedacht, nicht für Unternehmen. Für letztere gibt es die Agenturen-Seite (https://redaxo.org/support/agenturen/), aber dort seid ihr bereits drauf, habe ich gesehen.

Jedenfalls: Jeder Eintrag sollte auf eine Person gemünzt sein. Wenn sie Teil eines Unternehmens sind, kann dieses gerne verlinkt werden, und es können auch alle den gleichen Standort auf der Karte haben. Nur sollen die Einträge sich auf die Personen beziehen und zeigen, wo überall auf der Welt Menschen mit REDAXO zu tun haben. :)

2021-04-03 18:02 UTC, schuer commented
Gibt es denn eine Person in Basel, die in irgendeiner Form mit REDAXO zu tun hat (z. B. auch als Redakteur*in), und die womöglich auf die Karte möchte?

2022-10-10 06:24 UTC, schuer requested changes
Noch aktuell?

2023-01-25 08:08 UTC, closed without merging

2023-01-25 08:39 UTC, dtpop commented
Danke @schuer für Dein Engagement. Ich weiß hier immer nicht so genau wo ich hinklicken muss - meistens bringe ich dann alles durcheinander ... Wenn der Eintrag ggf. sinnvoll ist, lege ich einen neuen an.
Lieber Gruß,
Wolfgang

2023-01-25 08:43 UTC, schuer commented
Hey @dtpop, in diesem Fall hat GitHub übrigens automatisch den PR geschlossen, weil ich den master-Branch in »main« umbenannt hatte.

Also wenn es bei Zephir Menschen gibt, die mit REDAXO arbeiten, und die Lust auf einen Eintrag auf der Karte haben, leg ruhig neue PRs an. Wichtig ist nur, dass es um Menschen geht, nicht um die Firma. ✌️