Update lux
FriendsOfREDAXO/community pull request #341
Opened 2022-04-24 10:28 UTC by LuxusMEDIA

2022-10-10 06:18 UTC, schuer requested changes
Der Eintrag ist leider zu werblich. Die Community-Karte soll auf Personen ausgerichtet sein, die REDAXO nutzen. Es geht um die Motivation dahinter, nicht um die Unternehmen.

Magst du das nochmal anpassen, @LuxusMEDIA ?

2022-10-10 08:10 UTC, LuxusMEDIA commented
@schuer Sorry. Ist jetzt geändert.

2022-10-10 08:26 UTC, schuer approved these changes

2022-10-10 08:26 UTC, merged

2022-10-10 08:29 UTC, schuer commented
@LuxusMEDIA Thx, jetzt sitzt du allerdings im Indischen Ozean? :)
https://friendsofredaxo.github.io/community/#lux

2022-10-13 06:33 UTC, schuer commented
@LuxusMEDIA Hab’s getauscht, aber jetzt sitzt du in Schweden :)

2022-10-13 07:19 UTC, LuxusMEDIA commented
@schuer Ja, das ist auch richtig. Ich mache gerade 2 Auslandssemester hier.